### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ICostaEx** [sentanos/roblox-js#14] opened 2017-01-27 06:14 UTC
I would like to make a few suggestions/additions to the main functions:
- onMessage() -- Executes when the bot receives a message (Use the ROBLOX notifications to catch this event maybe?)

- Addition to message() -- If the player cant be messaged, have the bot follow them and then try, if still no skip over that person.

**Comment by SparkleOff** [comment] 2017-01-27 11:27
onmessage suggestion will most likely not happen since when he is posting the data, he is using the motzilla bot, not google bot. basically he is using firefox instead of google which i am pretty sure the notification system isn't available for firefox. if i am wrong, my bad but i just still think this will not happen.

I like the second suggestion, but mostly everyone has it where you have to follow them to message them so the. best bet is to just make a follow function and execute it before sending the message instead of having it check. you can probably do that on your side anyways if he makes the follow function, you can just see if the message function returns an error than if it does than it will execute the follow function.

i will see if i can do a pull request for the follow function because it might be useful for me too.

**Comment by sentanos** [comment] 2017-01-27 20:02
1. onMessage is a very interesting suggestion and I will look into adding it. If ROBLOX does use WebSockets for notifications it shouldn't be a problem to fire an event for it
2. I'm not making your PM bot for you, this can all be done very easily with the current scripts (and the addition of a follow function, which is not complicated)

**Comment by sentanos** [comment] 2017-01-27 20:05
> he is using the motzilla bot, not google bot. basically he is using firefox instead of google which i am pretty sure the notification system isn't available for firefox

I have no idea what you are talking about here.

**Comment by ICostaEx** [comment] 2017-01-27 23:21
Also, Why is it that getPlayers() only returns a maximum of 12 users? I have my intervals set to 1000, and my delay set to 10000

**Comment by sentanos** [comment] 2017-01-27 23:23
It shouldn't, how are you calling it (what code are you using)?

**Comment by ICostaEx** [comment] 2017-01-27 23:26
` rbx.getPlayers(539310, 6).promise.then(players => {
            //Object.keys(players.players).forEach(function(key) {
              //console.log(key, players.players[key])
            //})
          
            Object.keys(players.players).map(function(key) {
              ++totalPromoted;
             // console.log(players.players[key])
              //rbx.message(players.players[key],"Sorry to inform you but..",letsHope);
              rbx.setRank(539310, players.players[key], 3);
           })`

The role itself has only 6k people in it. Im trying to demoted them all down >.>

**Comment by sentanos** [comment] 2017-01-27 23:44
Use `node -v` to get your node.js version and post it here.

**Comment by ICostaEx** [comment] 2017-01-27 23:44
7.4.0

**Comment by sentanos** [comment] 2017-01-27 23:52
I have confirmed the error and will look into it. It seems to only be happening with this specific group.

**Comment by sentanos** [comment] 2017-01-28 00:33
I fixed the error and will update the module soon. What still confuses me is that on other groups getPlayers still works fine but on this one I had to add something.

**Comment by sentanos** [comment] 2017-01-28 00:37
If you don't mind waiting I'd like to push the update along with some other new functions which could take a little longer to finish. If you are in a hurry just me know and I'll give you the fixed file for you to update manually.

**Comment by ICostaEx** [comment] 2017-01-28 04:06
Up to you, It would help me out a bit but if you dont feel like going through the trouble its fine.

**Comment by sentanos** [comment] 2017-01-28 04:08
I won't update the module just yet but [here](https://gist.github.com/sentanos/29513127af7ffa6b65bcedf6fe4ca6a7) is the fixed getPlayers.js file which you can update on your local machine by going to node_modules>roblox-js>lib and replacing the existing getPlayers.js file with the one I linked.

**Comment by ICostaEx** [comment] 2017-01-28 04:11
Thank you!

**Comment by ICostaEx** [comment] 2017-01-30 03:51
Also another suggestion for the message() function add the ability to add a delay so you dont get the "You are sending messages too quickly" error

**Comment by sentanos** [comment] 2017-01-30 03:53
In fact I was already working on this and it will be included in 3.0

**Closed as completed** 2017-02-23 20:42 UTC
Labels: enhancement
