### ISSUE TITLE
Understanding this error?

### ISSUE THREAD

**Issue by ytomasch** [sentanos/roblox-js#41] opened 2017-07-29 08:24 UTC
![image](https://user-images.githubusercontent.com/7379790/28743317-20af66ca-7415-11e7-8cb8-1c2efaad67b9.png)

I am unable to understand what is occuring here, the script prints that the node logged in, got the token, and sent the payout. Yet no payout, and this error...

**Comment by sentanos** [comment] 2017-07-29 15:43
This is a known issue caused by a recent ROBLOX update. I already fixed it but haven't released the next version yet. I will be patching this on v3 soon before releasing v4 shortly after.

**Comment by ytomasch** [comment] 2017-07-31 18:52
When do you believe this will be patched?

**Comment by sentanos** [comment] 2017-07-31 19:12
Today

**Comment by sentanos** [comment] 2017-08-01 00:08
Fixed in 3.0.7

**Closed as completed by sentanos** 2017-08-01 00:08 UTC
